# Generated by Django 3.0 on 2020-10-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=100, unique=True)),
                ('mdesc', models.TextField(blank=True, null=True)),
                ('ming', models.CharField(max_length=120)),
                ('mlink', models.CharField(max_length=200)),
            ],
        ),
    ]
